services:
  db:
    image: postgres:latest
    container_name: moon-shop-db
    environment:
      POSTGRES_USER: moon-shop
      POSTGRES_PASSWORD: changeit
      POSTGRES_DB: moon-shop
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U moon-shop" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: moon-shop
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      LAPIS_ENVIRONMENT: development
